name: build-napi

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target x86_64-apple-darwin -o ./dist
          - host: windows-latest
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target x86_64-pc-windows-msvc -o ./dist
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target i686-pc-windows-msvc -o ./dist
            target: i686-pc-windows-msvc
          - host: windows-latest
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target aarch64-pc-windows-msvc -o ./dist
            target: aarch64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target x86_64-unknown-linux-gnu --use-napi-cross -o ./dist
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target x86_64-unknown-linux-musl -x -o ./dist
          - host: macos-latest
            target: aarch64-apple-darwin
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target aarch64-apple-darwin -o ./dist
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target aarch64-unknown-linux-gnu --use-napi-cross -o ./dist
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine-aarch64
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target aarch64-unknown-linux-musl -x -o ./dist
          - host: ubuntu-latest
            target: aarch64-linux-android
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target aarch64-linux-android -o ./dist
          - host: ubuntu-latest
            target: wasm32-wasip1-threads
            build: pnpm -F @open-spaced-repetition/binding exec napi build --platform --release --target wasm32-wasip1-threads -o ./dist


    runs-on: ${{ matrix.settings.host }}
    name: stable - ${{ matrix.settings.target }} - node@${{ inputs['node-version'] }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/reusable/pnpm.yml
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - uses: mlugg/setup-zig@v2
        if: ${{ contains(matrix.settings.target, 'musl') }}
        with:
          version: 0.15.1

      - name: Install cargo-zigbuild
        uses: taiki-e/install-action@v2
        if: ${{ contains(matrix.settings.target, 'musl') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild

      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup pnpm (x86)
        if: matrix.settings.target == 'i686-pc-windows-msvc'
        shell: bash
        run: npm install -g corepack@0.32.0 --force && corepack enable pnpm

      - name: Setup node x86
        uses: actions/setup-node@v4
        if: matrix.settings.target == 'i686-pc-windows-msvc'
        with:
          node-version: 20
          cache: 'pnpm'
          architecture: x86

      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: matrix.settings.target != 'wasm32-wasip1-threads'
        with:
          name: bindings-${{ matrix.settings.target }}
          path: |
            packages/binding/dist/*.node
            packages/binding/dist/*.js
            packages/binding/dist/*.d.ts
            packages/binding/dist/*.cjs
            packages/binding/dist/*.mjs
          if-no-files-found: error
      - name: Upload WASI artifact
        uses: actions/upload-artifact@v4
        if: matrix.settings.target == 'wasm32-wasip1-threads'
        with:
          name: bindings-${{ matrix.settings.target }}
          path: |
            packages/binding/dist/*.wasm
            packages/binding/dist/*.js
            packages/binding/dist/*.d.ts
            packages/binding/dist/*.cjs
            packages/binding/dist/*.mjs
          if-no-files-found: error