name: setup-node-pnpm
description: Setup Node.js and pnpm with workspace install caching

inputs:
  node-version:
    description: Node version to use
    required: false
    default: '20'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Enable pnpm
      run: npm install -g corepack@0.32.0 --force && corepack enable pnpm
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash