# To avoid polluting the root pnpm-lock.yaml, I added a pnpm-workspace.yaml file inside each example.
packages:
  - .

allowBuilds:
  sharp: true

minimumReleaseAgeExclude:
  - '@napi-rs/wasm-runtime@1.2.0'

supportedArchitectures:
  cpu: [ current, wasm32 ]
