@startuml FSRSAlgorithmFunctionCalls

FSRSAlgorithm -down-> init_ds
init_ds -down-> init_difficulty
init_ds -down-> init_stability
FSRSAlgorithm -down-> next_ds
FSRSAlgorithm -down-> current_retrievability
FSRSAlgorithm -down-> next_interval
next_interval -down-> apply_fuzz
next_ds -down-> next_difficulty
next_ds -down-> next_forget_stability
next_ds -down-> next_recall_stability
next_difficulty -down-> constrain_difficulty
next_difficulty -down-> mean_reversion

@enduml
